language: node_js
node_js:
  - "8"
sudo: false
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - echo 'eslint' && echo -en 'travis_fold:start:script.eslint\\r'
  - npm run eslint
  - echo -en 'travis_fold:end:script.eslint\\r'

  - echo 'test webgl-stub' && echo -en 'travis_fold:start:script.test\\r'
  - npm run build
  - npm run test -- --browsers Electron --webgl-stub --failTaskOnError --suppressPassed
  - echo -en 'travis_fold:end:script.test\\r'

  - echo 'release' && echo -en 'travis_fold:start:script.release\\r'
  - npm run clean
  - npm run release -- --concurrency 2
  - echo -en 'travis_fold:end:script.release\\r'

  - echo 'test webgl-stub release' && echo -en 'travis_fold:start:script test.release\\r'
  - npm run test -- --browsers Electron --failTaskOnError --webgl-stub --release --suppressPassed
  - echo -en 'travis_fold:end:script test.release\\r'

  - echo 'cloc' && echo -en 'travis_fold:start:script.cloc\\r'
  - npm run cloc
  - echo -en 'travis_fold:end:script.cloc\\r'
